from app.domain.exceptions import InvalidTelemetryUploadError

TRACKZEE_COLUMNS: tuple[str, ...] = (
    "fetched_at",
    "Imeino",
    "Vehicle_No",
    "Vehicle_Name",
    "Company",
    "Branch",
    "Vehicletype",
    "DeviceModel",
    "Status",
    "Power",
    "IGN",
    "GPS",
    "Speed",
    "Angle",
    "course",
    "Odometer",
    "can_odometer",
    "Latitude",
    "Longitude",
    "Location",
    "POI",
    "GPSActualTime",
    "Datetime",
    "Temperature",
    "ExternalVolt",
    "battery_percentage",
    "satellite_count",
    "gps_hdop",
    "Fuel",
    "AC",
    "SOS",
    "Immobilize_State",
    "Door1",
    "Door2",
    "Door3",
    "Door4",
    "elock",
    "Driver_First_Name",
    "Driver_Middle_Name",
    "Driver_Last_Name",
    "Ibutton/RFID",
    "Vin",
    "mcc",
    "mnc",
    "cellid",
    "lac",
    "heartbeat",
    "username",
    "Altitude",
)

TRACKZEE_TO_DOMAIN_FIELD_MAP: dict[str, str] = {
    "fetched_at": "fetched_at",
    "Imeino": "device_imei",
    "Vehicle_No": "vehicle_registration",
    "Vehicle_Name": "vehicle_name",
    "Company": "company_name",
    "Branch": "branch_name",
    "Vehicletype": "vehicle_type",
    "DeviceModel": "device_model",
    "Status": "vehicle_status",
    "Power": "power_state",
    "IGN": "ignition_state",
    "GPS": "gps_state",
    "Speed": "speed_kph",
    "Angle": "heading_angle",
    "course": "course",
    "Odometer": "odometer",
    "can_odometer": "can_odometer",
    "Latitude": "latitude",
    "Longitude": "longitude",
    "Location": "location_text",
    "POI": "point_of_interest",
    "GPSActualTime": "gps_actual_time",
    "Datetime": "recorded_at",
    "Temperature": "temperature",
    "ExternalVolt": "external_voltage",
    "battery_percentage": "battery_percentage",
    "satellite_count": "satellite_count",
    "gps_hdop": "gps_hdop",
    "Fuel": "fuel_level",
    "AC": "ac_state",
    "SOS": "sos_state",
    "Immobilize_State": "immobilize_state",
    "Door1": "door_1_state",
    "Door2": "door_2_state",
    "Door3": "door_3_state",
    "Door4": "door_4_state",
    "elock": "electronic_lock_state",
    "Driver_First_Name": "driver_first_name",
    "Driver_Middle_Name": "driver_middle_name",
    "Driver_Last_Name": "driver_last_name",
    "Ibutton/RFID": "driver_ibutton_rfid",
    "Vin": "vin",
    "mcc": "mobile_country_code",
    "mnc": "mobile_network_code",
    "cellid": "cell_id",
    "lac": "location_area_code",
    "heartbeat": "heartbeat",
    "username": "source_username",
    "Altitude": "altitude",
}


def validate_trackzee_header(header: list[str]) -> None:
    if tuple(header) != TRACKZEE_COLUMNS:
        raise InvalidTelemetryUploadError(
            "CSV header does not match the required Trackzee export format."
        )
